AWSTemplateFormatVersion: '2010-09-09'
Description: 's3 bucket'

Parameters:
 Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MysamBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: GithubActions
  Outputs:
    BucketName:
      Description: Bucket Name
      Value: !Ref MysamBucket

 