AWSTemplateFormatVersion: '2010-09-09'
Description: 's3 bucket'

Parameters:
 Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-${Environment}-bucket'
      Tags:
        - Key: Environment
          Value: !Ref Environment
  Outpost:
    BucketName:
      Description: Bucket Name
      Value: !Ref MyS3Bucket

 