AWSTemplateFormatVersion: '2010-09-09'
Description: 's3 bucket'

Parameters:
 Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  GAS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "my-bucket-${Environment}"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: GithubActionsTesting
 
  Outputs:
    BucketName:
      Description: 'Name of created S3 Bucket'
      Value: !Ref S3Bucket