AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket'

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: GithubActions

Outputs:
  BucketName:
    Description: The name of the S3 bucket
    Value: !Ref MyS3Bucket



 