
name: Deploy AWS Lambda
  
on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
       
          
      