
name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'    
          
jobs:
  deploy-lambda: # name of our job
    runs-on: ubuntu-lastest #Sets or Specifies the runner
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python #Setsup our python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 
                
      - name: Install Dependencies  #Install any packages
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirments.txt -t lambda/

      - name: Configure AWS Creds #Sets up our AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
                 
      - name: Deploy Lambda Function #Zips lambda Directory and updates lambda function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name My-Lambda-cicd --zip-file fileb://lambda.zip





    